DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;
CREATE TABLE MYBOARD(
	MYNO NUMBER 				PRIMARY KEY,
	MYNAME VARCHAR2(1000) 		NOT NULL,
	MYTITLE VARCHAR2(2000) 		NOT NULL,
	MYCONTENT VARCHAR2(4000) 	NOT NULL,
	MYDATE DATE 				NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL,'관리자','스프링 테스트','spring mvc 어렵다',SYSDATE);

SELECT * FROM MYBOARD;


-----------------------------------------------------------------------------------
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER;
CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL


);

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'admin','1234','관리자');

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'kh','kh','일반');



SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME
FROM MYMEMBER;

SELECT * FROM MYMEMBER;

CREATE SEQUENCE TESTSEQ;
CREATE TABLE TESTBOARD(
	T_NO NUMBER 				PRIMARY KEY,
	T_NAME VARCHAR2(1000) 		NOT NULL,
	T_TITLE VARCHAR2(2000) 		NOT NULL,
	T_ITEM VARCHAR2(2) 	NOT NULL,
	T_PICTURE VARCHAR2(2000) NOT NULL,
	T_CONTENT VARCHAR2(4000) NOT NULL,
	T_ADDRESS VARCHAR2(3000) NOT NULL,
	
	
	CONSTRAINT TESTBOARD_AGENTCHK_ENABLED CHECK(T_ITEM IN ('Y', 'N'))
);

SELECT *
  	FROM TESTBOARD;
  
SELECT * FROM testboard;

INSERT INTO TESTBOARD VALUES(TESTSEQ.NEXTVAL, '김동주', '이천에서 제일 싼집', 'N', 'resources/user/img/testupload/ex_hoban.jpg','이천에서 제일 쌉니다 ㅎ 호반베르디움','경기도 이천시 마장면 오천리 14-2')

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
  	FROM MYMYBOARD
  	ORDER BY MYNO DESC;







